[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install",
  "cd shared && npm install && npm run build",
  "cd ../server && npm install"
]

[phases.build]
cmds = [
  "cd server && npm run build"
]

[start]
cmd = "cd server && npm start"

